/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudCommonOperationMetadata
 */
public class GoogleCloudCommonOperationMetadataTest {
    private final GoogleCloudCommonOperationMetadata model = new GoogleCloudCommonOperationMetadata();

    /**
     * Model tests for GoogleCloudCommonOperationMetadata
     */
    @Test
    public void testGoogleCloudCommonOperationMetadata() {
        // TODO: test GoogleCloudCommonOperationMetadata
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'cancelRequested'
     */
    @Test
    public void cancelRequestedTest() {
        // TODO: test cancelRequested
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'statusDetail'
     */
    @Test
    public void statusDetailTest() {
        // TODO: test statusDetail
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

    /**
     * Test the property 'verb'
     */
    @Test
    public void verbTest() {
        // TODO: test verb
    }

}
