/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GoogleIamV1PolicyDelta;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleIamV1LoggingAuditData
 */
public class GoogleIamV1LoggingAuditDataTest {
    private final GoogleIamV1LoggingAuditData model = new GoogleIamV1LoggingAuditData();

    /**
     * Model tests for GoogleIamV1LoggingAuditData
     */
    @Test
    public void testGoogleIamV1LoggingAuditData() {
        // TODO: test GoogleIamV1LoggingAuditData
    }

    /**
     * Test the property 'policyDelta'
     */
    @Test
    public void policyDeltaTest() {
        // TODO: test policyDelta
    }

}
