/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleIamV2PolicyOperationMetadata
 */
public class GoogleIamV2PolicyOperationMetadataTest {
    private final GoogleIamV2PolicyOperationMetadata model = new GoogleIamV2PolicyOperationMetadata();

    /**
     * Model tests for GoogleIamV2PolicyOperationMetadata
     */
    @Test
    public void testGoogleIamV2PolicyOperationMetadata() {
        // TODO: test GoogleIamV2PolicyOperationMetadata
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

}
