/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GoogleIamAdminV1AuditDataPermissionDelta;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleIamAdminV1AuditData
 */
public class GoogleIamAdminV1AuditDataTest {
    private final GoogleIamAdminV1AuditData model = new GoogleIamAdminV1AuditData();

    /**
     * Model tests for GoogleIamAdminV1AuditData
     */
    @Test
    public void testGoogleIamAdminV1AuditData() {
        // TODO: test GoogleIamAdminV1AuditData
    }

    /**
     * Test the property 'permissionDelta'
     */
    @Test
    public void permissionDeltaTest() {
        // TODO: test permissionDelta
    }

}
