/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleIamAdminV1AuditDataPermissionDelta
 */
public class GoogleIamAdminV1AuditDataPermissionDeltaTest {
    private final GoogleIamAdminV1AuditDataPermissionDelta model = new GoogleIamAdminV1AuditDataPermissionDelta();

    /**
     * Model tests for GoogleIamAdminV1AuditDataPermissionDelta
     */
    @Test
    public void testGoogleIamAdminV1AuditDataPermissionDelta() {
        // TODO: test GoogleIamAdminV1AuditDataPermissionDelta
    }

    /**
     * Test the property 'addedPermissions'
     */
    @Test
    public void addedPermissionsTest() {
        // TODO: test addedPermissions
    }

    /**
     * Test the property 'removedPermissions'
     */
    @Test
    public void removedPermissionsTest() {
        // TODO: test removedPermissions
    }

}
