/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GoogleTypeExpr;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleIamV2DenyRule
 */
public class GoogleIamV2DenyRuleTest {
    private final GoogleIamV2DenyRule model = new GoogleIamV2DenyRule();

    /**
     * Model tests for GoogleIamV2DenyRule
     */
    @Test
    public void testGoogleIamV2DenyRule() {
        // TODO: test GoogleIamV2DenyRule
    }

    /**
     * Test the property 'denialCondition'
     */
    @Test
    public void denialConditionTest() {
        // TODO: test denialCondition
    }

    /**
     * Test the property 'deniedPermissions'
     */
    @Test
    public void deniedPermissionsTest() {
        // TODO: test deniedPermissions
    }

    /**
     * Test the property 'deniedPrincipals'
     */
    @Test
    public void deniedPrincipalsTest() {
        // TODO: test deniedPrincipals
    }

    /**
     * Test the property 'exceptionPermissions'
     */
    @Test
    public void exceptionPermissionsTest() {
        // TODO: test exceptionPermissions
    }

    /**
     * Test the property 'exceptionPrincipals'
     */
    @Test
    public void exceptionPrincipalsTest() {
        // TODO: test exceptionPrincipals
    }

}
