/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GoogleIamV1PolicyDelta;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Audit log information specific to Cloud IAM. This message is serialized as an &#x60;Any&#x60; type in the &#x60;ServiceData&#x60; message of an &#x60;AuditLog&#x60; message.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:02:31.171999+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GoogleIamV1LoggingAuditData {
  public static final String SERIALIZED_NAME_POLICY_DELTA = "policyDelta";
  @SerializedName(SERIALIZED_NAME_POLICY_DELTA)
  @javax.annotation.Nullable
  private GoogleIamV1PolicyDelta policyDelta;

  public GoogleIamV1LoggingAuditData() {
  }

  public GoogleIamV1LoggingAuditData policyDelta(@javax.annotation.Nullable GoogleIamV1PolicyDelta policyDelta) {
    this.policyDelta = policyDelta;
    return this;
  }

  /**
   * Get policyDelta
   * @return policyDelta
   */
  @javax.annotation.Nullable
  public GoogleIamV1PolicyDelta getPolicyDelta() {
    return policyDelta;
  }

  public void setPolicyDelta(@javax.annotation.Nullable GoogleIamV1PolicyDelta policyDelta) {
    this.policyDelta = policyDelta;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoogleIamV1LoggingAuditData googleIamV1LoggingAuditData = (GoogleIamV1LoggingAuditData) o;
    return Objects.equals(this.policyDelta, googleIamV1LoggingAuditData.policyDelta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyDelta);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoogleIamV1LoggingAuditData {\n");
    sb.append("    policyDelta: ").append(toIndentedString(policyDelta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("policyDelta"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GoogleIamV1LoggingAuditData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GoogleIamV1LoggingAuditData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoogleIamV1LoggingAuditData is not found in the empty JSON string", GoogleIamV1LoggingAuditData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GoogleIamV1LoggingAuditData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GoogleIamV1LoggingAuditData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `policyDelta`
      if (jsonObj.get("policyDelta") != null && !jsonObj.get("policyDelta").isJsonNull()) {
        GoogleIamV1PolicyDelta.validateJsonElement(jsonObj.get("policyDelta"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoogleIamV1LoggingAuditData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoogleIamV1LoggingAuditData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoogleIamV1LoggingAuditData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoogleIamV1LoggingAuditData.class));

       return (TypeAdapter<T>) new TypeAdapter<GoogleIamV1LoggingAuditData>() {
           @Override
           public void write(JsonWriter out, GoogleIamV1LoggingAuditData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GoogleIamV1LoggingAuditData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GoogleIamV1LoggingAuditData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GoogleIamV1LoggingAuditData
   * @throws IOException if the JSON string is invalid with respect to GoogleIamV1LoggingAuditData
   */
  public static GoogleIamV1LoggingAuditData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoogleIamV1LoggingAuditData.class);
  }

  /**
   * Convert an instance of GoogleIamV1LoggingAuditData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

