/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A PermissionDelta message to record the added_permissions and removed_permissions inside a role.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:02:31.171999+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GoogleIamAdminV1AuditDataPermissionDelta {
  public static final String SERIALIZED_NAME_ADDED_PERMISSIONS = "addedPermissions";
  @SerializedName(SERIALIZED_NAME_ADDED_PERMISSIONS)
  @javax.annotation.Nullable
  private List<String> addedPermissions = new ArrayList<>();

  public static final String SERIALIZED_NAME_REMOVED_PERMISSIONS = "removedPermissions";
  @SerializedName(SERIALIZED_NAME_REMOVED_PERMISSIONS)
  @javax.annotation.Nullable
  private List<String> removedPermissions = new ArrayList<>();

  public GoogleIamAdminV1AuditDataPermissionDelta() {
  }

  public GoogleIamAdminV1AuditDataPermissionDelta addedPermissions(@javax.annotation.Nullable List<String> addedPermissions) {
    this.addedPermissions = addedPermissions;
    return this;
  }

  public GoogleIamAdminV1AuditDataPermissionDelta addAddedPermissionsItem(String addedPermissionsItem) {
    if (this.addedPermissions == null) {
      this.addedPermissions = new ArrayList<>();
    }
    this.addedPermissions.add(addedPermissionsItem);
    return this;
  }

  /**
   * Added permissions.
   * @return addedPermissions
   */
  @javax.annotation.Nullable
  public List<String> getAddedPermissions() {
    return addedPermissions;
  }

  public void setAddedPermissions(@javax.annotation.Nullable List<String> addedPermissions) {
    this.addedPermissions = addedPermissions;
  }


  public GoogleIamAdminV1AuditDataPermissionDelta removedPermissions(@javax.annotation.Nullable List<String> removedPermissions) {
    this.removedPermissions = removedPermissions;
    return this;
  }

  public GoogleIamAdminV1AuditDataPermissionDelta addRemovedPermissionsItem(String removedPermissionsItem) {
    if (this.removedPermissions == null) {
      this.removedPermissions = new ArrayList<>();
    }
    this.removedPermissions.add(removedPermissionsItem);
    return this;
  }

  /**
   * Removed permissions.
   * @return removedPermissions
   */
  @javax.annotation.Nullable
  public List<String> getRemovedPermissions() {
    return removedPermissions;
  }

  public void setRemovedPermissions(@javax.annotation.Nullable List<String> removedPermissions) {
    this.removedPermissions = removedPermissions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoogleIamAdminV1AuditDataPermissionDelta googleIamAdminV1AuditDataPermissionDelta = (GoogleIamAdminV1AuditDataPermissionDelta) o;
    return Objects.equals(this.addedPermissions, googleIamAdminV1AuditDataPermissionDelta.addedPermissions) &&
        Objects.equals(this.removedPermissions, googleIamAdminV1AuditDataPermissionDelta.removedPermissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addedPermissions, removedPermissions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoogleIamAdminV1AuditDataPermissionDelta {\n");
    sb.append("    addedPermissions: ").append(toIndentedString(addedPermissions)).append("\n");
    sb.append("    removedPermissions: ").append(toIndentedString(removedPermissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("addedPermissions", "removedPermissions"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GoogleIamAdminV1AuditDataPermissionDelta
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GoogleIamAdminV1AuditDataPermissionDelta.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoogleIamAdminV1AuditDataPermissionDelta is not found in the empty JSON string", GoogleIamAdminV1AuditDataPermissionDelta.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GoogleIamAdminV1AuditDataPermissionDelta.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GoogleIamAdminV1AuditDataPermissionDelta` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("addedPermissions") != null && !jsonObj.get("addedPermissions").isJsonNull() && !jsonObj.get("addedPermissions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `addedPermissions` to be an array in the JSON string but got `%s`", jsonObj.get("addedPermissions").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("removedPermissions") != null && !jsonObj.get("removedPermissions").isJsonNull() && !jsonObj.get("removedPermissions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `removedPermissions` to be an array in the JSON string but got `%s`", jsonObj.get("removedPermissions").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoogleIamAdminV1AuditDataPermissionDelta.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoogleIamAdminV1AuditDataPermissionDelta' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoogleIamAdminV1AuditDataPermissionDelta> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoogleIamAdminV1AuditDataPermissionDelta.class));

       return (TypeAdapter<T>) new TypeAdapter<GoogleIamAdminV1AuditDataPermissionDelta>() {
           @Override
           public void write(JsonWriter out, GoogleIamAdminV1AuditDataPermissionDelta value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GoogleIamAdminV1AuditDataPermissionDelta read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GoogleIamAdminV1AuditDataPermissionDelta given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GoogleIamAdminV1AuditDataPermissionDelta
   * @throws IOException if the JSON string is invalid with respect to GoogleIamAdminV1AuditDataPermissionDelta
   */
  public static GoogleIamAdminV1AuditDataPermissionDelta fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoogleIamAdminV1AuditDataPermissionDelta.class);
  }

  /**
   * Convert an instance of GoogleIamAdminV1AuditDataPermissionDelta to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

