/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GoogleIamV2DenyRule;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A single rule in a &#x60;Policy&#x60;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:02:31.171999+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GoogleIamV2PolicyRule {
  public static final String SERIALIZED_NAME_DENY_RULE = "denyRule";
  @SerializedName(SERIALIZED_NAME_DENY_RULE)
  @javax.annotation.Nullable
  private GoogleIamV2DenyRule denyRule;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public GoogleIamV2PolicyRule() {
  }

  public GoogleIamV2PolicyRule denyRule(@javax.annotation.Nullable GoogleIamV2DenyRule denyRule) {
    this.denyRule = denyRule;
    return this;
  }

  /**
   * Get denyRule
   * @return denyRule
   */
  @javax.annotation.Nullable
  public GoogleIamV2DenyRule getDenyRule() {
    return denyRule;
  }

  public void setDenyRule(@javax.annotation.Nullable GoogleIamV2DenyRule denyRule) {
    this.denyRule = denyRule;
  }


  public GoogleIamV2PolicyRule description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * A user-specified description of the rule. This value can be up to 256 characters.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoogleIamV2PolicyRule googleIamV2PolicyRule = (GoogleIamV2PolicyRule) o;
    return Objects.equals(this.denyRule, googleIamV2PolicyRule.denyRule) &&
        Objects.equals(this.description, googleIamV2PolicyRule.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(denyRule, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoogleIamV2PolicyRule {\n");
    sb.append("    denyRule: ").append(toIndentedString(denyRule)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("denyRule", "description"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GoogleIamV2PolicyRule
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GoogleIamV2PolicyRule.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoogleIamV2PolicyRule is not found in the empty JSON string", GoogleIamV2PolicyRule.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GoogleIamV2PolicyRule.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GoogleIamV2PolicyRule` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `denyRule`
      if (jsonObj.get("denyRule") != null && !jsonObj.get("denyRule").isJsonNull()) {
        GoogleIamV2DenyRule.validateJsonElement(jsonObj.get("denyRule"));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoogleIamV2PolicyRule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoogleIamV2PolicyRule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoogleIamV2PolicyRule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoogleIamV2PolicyRule.class));

       return (TypeAdapter<T>) new TypeAdapter<GoogleIamV2PolicyRule>() {
           @Override
           public void write(JsonWriter out, GoogleIamV2PolicyRule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GoogleIamV2PolicyRule read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GoogleIamV2PolicyRule given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GoogleIamV2PolicyRule
   * @throws IOException if the JSON string is invalid with respect to GoogleIamV2PolicyRule
   */
  public static GoogleIamV2PolicyRule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoogleIamV2PolicyRule.class);
  }

  /**
   * Convert an instance of GoogleIamV2PolicyRule to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

