/*
 * Identity and Access Management (IAM) API
 * Manages identity and access control for Google Cloud Platform resources, including the creation of service accounts, which you can use to authenticate to Google and make API calls. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GoogleIamV1BindingDelta;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The difference delta between two policies.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:02:31.171999+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GoogleIamV1PolicyDelta {
  public static final String SERIALIZED_NAME_BINDING_DELTAS = "bindingDeltas";
  @SerializedName(SERIALIZED_NAME_BINDING_DELTAS)
  @javax.annotation.Nullable
  private List<GoogleIamV1BindingDelta> bindingDeltas = new ArrayList<>();

  public GoogleIamV1PolicyDelta() {
  }

  public GoogleIamV1PolicyDelta bindingDeltas(@javax.annotation.Nullable List<GoogleIamV1BindingDelta> bindingDeltas) {
    this.bindingDeltas = bindingDeltas;
    return this;
  }

  public GoogleIamV1PolicyDelta addBindingDeltasItem(GoogleIamV1BindingDelta bindingDeltasItem) {
    if (this.bindingDeltas == null) {
      this.bindingDeltas = new ArrayList<>();
    }
    this.bindingDeltas.add(bindingDeltasItem);
    return this;
  }

  /**
   * The delta for Bindings between two policies.
   * @return bindingDeltas
   */
  @javax.annotation.Nullable
  public List<GoogleIamV1BindingDelta> getBindingDeltas() {
    return bindingDeltas;
  }

  public void setBindingDeltas(@javax.annotation.Nullable List<GoogleIamV1BindingDelta> bindingDeltas) {
    this.bindingDeltas = bindingDeltas;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoogleIamV1PolicyDelta googleIamV1PolicyDelta = (GoogleIamV1PolicyDelta) o;
    return Objects.equals(this.bindingDeltas, googleIamV1PolicyDelta.bindingDeltas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bindingDeltas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoogleIamV1PolicyDelta {\n");
    sb.append("    bindingDeltas: ").append(toIndentedString(bindingDeltas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("bindingDeltas"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GoogleIamV1PolicyDelta
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GoogleIamV1PolicyDelta.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoogleIamV1PolicyDelta is not found in the empty JSON string", GoogleIamV1PolicyDelta.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GoogleIamV1PolicyDelta.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GoogleIamV1PolicyDelta` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("bindingDeltas") != null && !jsonObj.get("bindingDeltas").isJsonNull()) {
        JsonArray jsonArraybindingDeltas = jsonObj.getAsJsonArray("bindingDeltas");
        if (jsonArraybindingDeltas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("bindingDeltas").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `bindingDeltas` to be an array in the JSON string but got `%s`", jsonObj.get("bindingDeltas").toString()));
          }

          // validate the optional field `bindingDeltas` (array)
          for (int i = 0; i < jsonArraybindingDeltas.size(); i++) {
            GoogleIamV1BindingDelta.validateJsonElement(jsonArraybindingDeltas.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoogleIamV1PolicyDelta.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoogleIamV1PolicyDelta' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoogleIamV1PolicyDelta> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoogleIamV1PolicyDelta.class));

       return (TypeAdapter<T>) new TypeAdapter<GoogleIamV1PolicyDelta>() {
           @Override
           public void write(JsonWriter out, GoogleIamV1PolicyDelta value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GoogleIamV1PolicyDelta read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GoogleIamV1PolicyDelta given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GoogleIamV1PolicyDelta
   * @throws IOException if the JSON string is invalid with respect to GoogleIamV1PolicyDelta
   */
  public static GoogleIamV1PolicyDelta fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoogleIamV1PolicyDelta.class);
  }

  /**
   * Convert an instance of GoogleIamV1PolicyDelta to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

